### ISSUE TITLE
Module plugin beat_dashboards_setup delete all custom dashboards

### ISSUE THREAD

**Issue by BartokIT** [BartokIT/ansible.elastic#2]
### Describe the bug

When using the _beat_dashboards_setup_ module all the dashboards not listed as input will be deleted.

The right behaviour of the module is to manage only dashboards included with the beat agent, so only those must be eventually deleted.

### To reproduce

Suppose you have two dashboard:

- "[Metricbeat System] Host overview ECS"
- Custom dashboard

The execution of the following code:

```yaml
- name: Manage Beat dashboards
  bartokit.elastic.beat_dashboards_setup:
    user: 'api_user'
    password: "api_password"
    ssl_verify: false
    dashboards:
      '[Metricbeat System] Host overview ECS':
        beat: metricbeat
        namespaces:
          - default      
```

will remove the custom dashboard
